# Generated by Django 3.2.9 on 2021-11-10 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('appId', models.AutoField(primary_key=True, serialize=False)),
                ('appName', models.CharField(db_column='appName', default='', max_length=128, null=True)),
                ('appImage', models.ImageField(blank=True, db_column='appImage', null=True, upload_to='')),
                ('appExplain', models.TextField(db_column='explain', null=True)),
                ('category', models.CharField(choices=[('media', '동영상 및 사진 서비스'), ('sns', '소통 서비스'), ('benefit', '혜택 서비스'), ('shopping', '쇼핑 서비스'), ('finance', '금융 서비스'), ('health', '건강 서비스'), ('map', '지도 서비스'), ('others', '기타 서비스')], max_length=50)),
                ('company_name', models.ForeignKey(db_column='company_name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('qnaId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='title', default='')),
                ('question', models.TextField(db_column='question')),
                ('answer', models.TextField(db_column='answer')),
                ('qDate', models.DateTimeField(auto_now_add=True, db_column='qDate')),
                ('aDate', models.DateTimeField(db_column='aDate')),
                ('checkAnswer', models.BooleanField(db_column='checkAnswer', default=False)),
                ('appName', models.ForeignKey(db_column='appName', on_delete=django.db.models.deletion.CASCADE, to='support.app')),
                ('q_personId', models.ForeignKey(db_column='personId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qna',
            },
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('guideId', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(blank=True, db_column='images', null=True, upload_to='')),
                ('explain', models.TextField(db_column='explain', null=True)),
                ('uploadDate', models.DateTimeField(auto_now_add=True, db_column='uploadDate')),
                ('is_Basic', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('appName', models.ForeignKey(db_column='appName', on_delete=django.db.models.deletion.CASCADE, to='support.app')),
            ],
            options={
                'db_table': 'guideline',
            },
        ),
    ]
