# Generated by Django 3.2.9 on 2021-11-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='aDate',
            field=models.DateTimeField(db_column='aDate', null=True),
        ),
    ]
