# Generated by Django 3.2.9 on 2021-11-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_qna_adate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideline',
            name='appName',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='aDate',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='appName',
        ),
        migrations.AddField(
            model_name='guideline',
            name='appId',
            field=models.ForeignKey(db_column='appId', default='', on_delete=django.db.models.deletion.CASCADE, to='support.app'),
        ),
        migrations.AddField(
            model_name='qna',
            name='appId',
            field=models.ForeignKey(db_column='appId', default='', on_delete=django.db.models.deletion.CASCADE, to='support.app'),
        ),
    ]
