# Generated by Django 3.2.9 on 2021-11-11 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_auto_20211111_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='company_name',
        ),
        migrations.AddField(
            model_name='app',
            name='companyId',
            field=models.ForeignKey(db_column='id', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
