# Generated by Django 3.2.9 on 2021-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20211115_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='funcName',
            field=models.TextField(db_column='funcName', default=''),
        ),
    ]
