# Generated by Django 3.2.9 on 2021-11-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_guideline_funcname'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='hits',
            field=models.PositiveIntegerField(db_column='hits', default=0, verbose_name='조회수'),
        ),
    ]
